# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: New Features
      labels:
        -kind:enhancement 
    - title: Bug Fixes
      labels:
        - kind:bug
    - title: Other
      labels:
        - "*"
