swagger: '2.0'
info:
  title: Elyra API
  description: The API for the Elyra extensions
  version: '1'
  contact:
    name: Elyra
    url: 'https://github.com/elyra-ai/elyra'
produces:
  - application/json
consumes:
  - application/json
parameters:
  namespace:
    name: namespace
    required: true
    in: path
    description: The name of the namespace
    type: string
  resource:
    name: resource
    required: true
    in: path
    description: The name of the resource in a given namespace
    type: string
paths:
  /api/elyra.yaml:
    get:
      produces:
        - text/x-yaml
      summary: Get API information (yaml)
      tags:
        - api
      responses:
        '200':
          description: Returns a swagger specification in yaml
  '/api/metadata/{namespace}':
    parameters:
      - $ref: '#/parameters/namespace'
    get:
      summary: Get metadata for a given namespace
      tags:
        - metadata
      responses:
        '200':
          description: Returns the metadata instances for a given namespace
          schema:
            type: object
            properties:
              namespace:
                type: array
                description: The name of the namespace.
                items:
                  $ref: '#/definitions/MetadataResource'
        '404':
          description: Namespace not found
  '/api/metadata/{namespace}/{resource}':
    parameters:
      - $ref: '#/parameters/namespace'
      - $ref: '#/parameters/resource'
    get:
      summary: Get a given metadata instance from a given namespace
      tags:
        - metadata
      responses:
        '200':
          description: >-
            Returns the metadata instances for a given resource in a given
            namespace
          schema:
            $ref: '#/definitions/MetadataResource'
        '404':
          description: Namespace/Resource not found
  '/api/metadata_schema/{namespace}':
    parameters:
      - $ref: '#/parameters/namespace'
    get:
      summary: Get schemas for a given namespace
      tags:
        - metadata
      responses:
        '200':
          description: Returns the schema instances for a given namespace
          schema:
            type: object
            properties:
              namespace:
                type: array
                description: The name of the namespace.
                items:
                  $ref: '#/definitions/SchemaResource'
        '404':
          description: Namespace not found
  '/api/metadata_schema/{namespace}/{resource}':
    parameters:
      - $ref: '#/parameters/namespace'
      - $ref: '#/parameters/resource'
    get:
      summary: Get a given schema instance from a given namespace
      tags:
        - metadata
      responses:
        '200':
          description: >-
            Returns the schema instance for a given resource in a given namespace
          schema:
            $ref: '#/definitions/SchemaResource'
        '404':
          description: Namespace/Resource not found
definitions:
  MetadataResource:
    description: The set of properties comprising a namespace resource entity
    required:
      - name
      - display_name
      - schema_name
    properties:
      name:
        type: string
        description: The canonical name of the resource
      display_name:
        type: string
        description: The display name of the resource
      schema_name:
        type: string
        description: The schema name used to validate the resource
      resource:
        type: string
        format: filename
        description: Path to json file containing resource definition
      metadata:
        type: object
        description: >-
          A free-form dictionary consisting of additional information about the
          resource.
  SchemaResource:
    description: The set of properties comprising a namespace resource entity
    required:
      - namespace
      - name
    properties:
      namespace:
        type: string
        description: The namespace of the resource
      name:
        type: string
        description: The canonical name of the resource
      properties:
        type: object
        description: >-
          A free-form dictionary consisting of additional information about the
          resource.
