# syntax=docker/dockerfile:experimental
#
# Copyright 2018-2022 Elyra Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Ubuntu 20.04.2 LTS (Focal Fossa)
# Repository: https://gallery.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter
FROM public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter:v1.4

USER root

# Install build dependencies
RUN apt-get -yq update \
 && apt-get -yq install --no-install-recommends \
    build-essential \
    curl \
    git \
    sudo \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# Install NodeJS
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - \
 && apt-get -yq update \
 && apt-get -yq install --no-install-recommends \
    nodejs \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# Install Yarn
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
 && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
 && apt-get -yq update \
 && apt-get -yq install --no-install-recommends \
    yarn \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

USER ${NB_USER}

# Copy Elyra source code
COPY --chown=${NB_USER} --chmod=0755 elyra /tmp/elyra/

# Install Elyra from source
RUN cd /tmp/elyra \
 && make install-all \
 && rm -rf $HOME/.cache/yarn \
 && rm -rf $HOME/.cache/Cypress \
 && rm -rf /tmp/elyra/node_modules \
 && rm -rf /opt/conda/share/jupyter/lab/staging/node_modules

# Install component examples catalog
#  - this wail fail if the 'kfp-examples' pip extra is not installed
RUN elyra-metadata create component-catalogs \
    --schema_name=elyra-kfp-examples-catalog \
    --display_name="Kubeflow Pipelines examples" \
    --runtime_type=KUBEFLOW_PIPELINES \
    --categories="['examples']"