#!/bin/bash
#
# Copyright 2018-2020 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
set -euo pipefail

export VERSION=1.22.4

# Download and install Yarn Package Manager
wget https://github.com/yarnpkg/yarn/releases/download/v${VERSION}/yarn-v${VERSION}.tar.gz
tar -zvxf yarn-v${VERSION}.tar.gz && rm -rf yarn-v${VERSION}.tar.gz

# Add to PATH
export PATH=$(pwd)/yarn-v${VERSION}/bin/:$PATH

# Build Elyra Distribution
make release

# Install Elyra Wheel
pip install dist/*.whl

# Rebuild Jupyter Lab to enable extensions
jupyter labextension link --no-build packages/application/
jupyter labextension link --no-build packages/ui-components/
jupyter lab build --dev-build=False --minimize=False
